from .article import Article
from .declension import Declension
from .frequency import Frequency
from .language import Language
from .mood import Mood
from .nouns import Nouns
from .sentence import Sentence
from .speech_part import SpeechPart
from .tense import Tense
from .translation import Translation
from .verb_conjugation import VerbConjugation
from .word import Word
from .word_sentence import WordSentence