# Generated by Django 5.1 on 2024-08-28 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.UUIDField(primary_key=True, serialize=False)),
                ('article_form', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Declension',
            fields=[
                ('declension_id', models.UUIDField(primary_key=True, serialize=False)),
                ('declension_predecessor', models.CharField(blank=True, max_length=20, null=True)),
                ('declension_person', models.TextField()),
                ('declension_form', models.CharField(max_length=50)),
                ('declension_taken_at', models.DateTimeField(blank=True, null=True)),
                ('declension_number', models.TextField()),
            ],
            options={
                'db_table': 'declension',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('frequency_id', models.UUIDField(primary_key=True, serialize=False)),
                ('frequency_label', models.CharField(max_length=50, unique=True)),
                ('frequency_lowest_class', models.IntegerField(unique=True)),
                ('frequency_highest_class', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'frequency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.UUIDField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=20, unique=True)),
                ('language_set_1_code', models.CharField(max_length=3, unique=True)),
                ('language_set_2t_code', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'db_table': 'language',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('mood_id', models.UUIDField(primary_key=True, serialize=False)),
                ('mood_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'mood',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_lemma', models.CharField(max_length=50)),
                ('word_id', models.UUIDField(primary_key=True, serialize=False)),
                ('word_initial_form', models.CharField(max_length=100, unique=True)),
                ('word_frequency_class', models.IntegerField(blank=True, null=True)),
                ('word_taken_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'word',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('sentence_id', models.UUIDField(primary_key=True, serialize=False)),
                ('sentence_form', models.TextField()),
            ],
            options={
                'db_table': 'sentence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpeechPart',
            fields=[
                ('speech_part_model_name', models.CharField(max_length=10, unique=True)),
                ('speech_part_name', models.CharField(max_length=30, unique=True)),
                ('speech_part_id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'speech_part',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tense',
            fields=[
                ('tense_id', models.UUIDField(primary_key=True, serialize=False)),
                ('tense_name', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'tense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VerbConjugation',
            fields=[
                ('verb_conjugation_id', models.UUIDField(primary_key=True, serialize=False)),
                ('verb_conjugation_voice', models.CharField(choices=[('active', 'Active'), ('passive', 'Passive')])),
                ('verb_conjugation_form', models.CharField(max_length=100)),
                ('verb_conjugation_person', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third')])),
                ('verb_conjugation_gender', models.CharField(blank=True, choices=[('masculine', 'Masculine'), ('feminine', 'Feminine'), ('neuter', 'Neuter'), ('common', 'Common')], null=True)),
                ('verb_conjugation_number', models.CharField(choices=[('singular', 'Singular'), ('plural', 'Plural')])),
                ('verb_conjugation_taken_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'verb_conjugation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nouns',
            fields=[
                ('noun_fk_word', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='wordLearner.word')),
                ('noun_plural', models.CharField(max_length=50)),
                ('noun_plural_taken_at', models.DateTimeField(blank=True, null=True)),
                ('noun_article_taken_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nouns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('translation_source', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='wordLearner.word')),
            ],
            options={
                'db_table': 'translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordSentence',
            fields=[
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='wordLearner.word')),
            ],
            options={
                'db_table': 'word_sentence',
                'managed': False,
            },
        ),
    ]
